export const FILTER_ACTION_TYPES = {
  CHANGE_FILTER_TITLE: 'CHANGE_FILTER_TITLE',
  CHANGE_FILTER_AUTHOR: 'CHANGE_FILTER_AUTHOR',
  SHOW_ONLY_FAVORITES: 'SHOW_ONLY_FAVORITES',
  RESET_FILTERS: 'RESET_FILTERS',
};
